language: viml
before_script:
    - vim --version
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    - git clone https://github.com/thinca/vim-themis

script:
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 autoload
    - vim-themis/bin/themis --reporter spec test/commands.vim test/parse.vim test/recipe.vim test/sample.vim test/tsort.vim
    - vim-themis/bin/themis --reporter spec test/source.vim
    - vim-themis/bin/themis --reporter spec test/lock.vim
